version: '3.9'

services:
  csv-verarbeiter:
    image: ghcr.io/donchrillo/csv_verarbeiter:latest
    container_name: csv-verarbeiter
    ports:
      - "8501:8501"
    volumes:
      - ./daten:/app/daten
    environment:
      - TZ=Europe/Berlin
      - PYTHONUNBUFFERED=1
      - SQL_SERVER=${SQL_SERVER}
      - SQL_PORT=${SQL_PORT}
      - SQL_DB=${SQL_DB}
      - SQL_USER=${SQL_USER}
      - SQL_PASS=${SQL_PASS}
    restart: unless-stopped
